import 'package:get/get.dart';
import 'package:flutter/material.dart';

class LocalizationService extends Translations {
  // Supported languages
  static final List<Locale> supportedLocales = [
    Locale('en', 'US'), // English
    Locale('ar', 'EG'), // Arabic
  ];

  // Default language
  static const Locale fallbackLocale = Locale('ar', 'EG');

  // Language Map
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'loading': 'Loading',
          'empty': 'EMPTY',
          'bottomBar.home': 'Home',
          'bottomBar.cart': 'Cart',
          'bottomBar.profile': 'Profile',
          'bottomBar.brands': 'Brands',
          'bottomBar.search': 'Search',
          'onBoardingScreen1.title': 'Shop Your Needs',
          'onBoardingScreen1.subTitle': 'Shop All Your Needs From One Place',
          'onBoardingScreen2.title': 'Shop Your Needs',
          'onBoardingScreen2.subTitle': 'Shop All Your Needs From One Place',
          'onBoardingScreen3.title': 'Shop Your Needs',
          'onBoardingScreen3.subTitle': 'Shop All Your Needs From One Place',
          'signinScreen.title': 'Welcome at 7 Days mart',
          'signinScreen.usernameTitle': 'Email or Phone',
          'signinScreen.password': 'Password',
          'signinScreen.forgetPassword': 'Forget Password?',
          'signinScreen.signinAction': 'Signin',
          'signinScreen.signupAction': 'Signup',
          'signupScreen.title': 'Welcome At 7DAYS MART',
          'signupScreen.usernameTitle': 'Email or Phone',
          'signupScreen.fullName': 'Full Name',
          'signupScreen.password': 'Password',
          'signupScreen.confirmPassword': 'Confirm Password',
          'signupScreen.phoneNumber': 'Phone',
          'signupScreen.address': 'Address',
          'signupScreen.signupAction': 'Signup',
          'signupScreen.signinAction': 'Signin',
          'change_language': 'Change Language',
          'languagesScreen.title': 'Choose Language',
          'languagesScreen.arabic': 'Arabic',
          'languagesScreen.english': 'English',
          'languagesScreen.continue': 'Continue',
          'unauthorizedDialog.title': 'Issue',
          'unauthorizedDialog.close': 'Close',
          'ViewErrorDialog.title': 'Alert',
          'ViewErrorDialog.close': 'Close',
          'homeScreen.searchFiled': 'What You Need',
          'homeScreen.offerAction': 'Read More',
          'homeScreen.title1': 'Shop By Category',
          'homeScreen.title2': 'popular',
          'searchPage.trendingAreTitle': 'Trending',
          'searchPage.popularSearchAreTitle': 'Popular Search',
          'searchPage.searchFiled': 'SEARCH YOU ...',
          'searchPage.title': 'SEARCH PRODUCT',
          'ProductDetailsScreen.title': 'PRODUCT DETAILS',
          'ProductDetailsScreen.descriptionTitle': 'Description',
          'ProductDetailsScreen.detailsTile': 'Details',
          'ProductDetailsScreen.price': 'Price',
          'ProductDetailsScreen.unit': 'SYP',
          'ProductDetailsScreen.specifications': 'Specifications',
          'ProductDetailsScreen.purchase': 'Purchase',
          'ProductDetailsScreen.addToCart': 'Add To Cart',
          'ProductDetailsScreen.removeFromCart': 'Add To Cart',
          'ProductDetailsScreen.QTY': 'Available Quantity',
          'ProductDetailsScreen.OOS': 'Out Of Stock',
          'cartScreen.title': 'CART',
          'cartScreen.deleteButton': 'Delete',
          'cartScreen.submit': 'Submit',
          'searchScreen.categories': 'Categories',
          'searchScreen.brands': 'Brands',
          'searchScreen.close': 'Done',
          'checkout.title': 'Order Checkut',
          'checkout.total': 'Total Cost',
          'checkout.proceed': 'Proceed',
          'checkout.Note': 'Notes',
          'checkout.mobile': 'Another Mobile',
          'profileScreen.orderHistory': 'Order History',
          'profileScreen.logout': 'Logout',
          'orderScreen.title': 'Order History',
          'brandScreen.title': 'Brands',
          'brandScreen.active': 'Active',
          'brandScreen.inactive': 'Inactive',
          'brandScreen.created': 'Created',
          'brandScreen.updated': 'Updated',
          'brandScreen.unknownBrand': 'Unknown Brand',
          'brandScreen.website': 'Website',
        },
        'ar_EG': {
          'loading': 'يرجى الانتظار',
          'empty': 'لا يوجد محتوى',
          'bottomBar.home': 'الرئيسية',
          'bottomBar.cart': 'السلة',
          'bottomBar.profile': 'الحساب',
          'bottomBar.brands': 'البراندات',
          'bottomBar.search': 'البحث',
          'onBoardingScreen1.title': 'تسوق حسب حاجتك',
          'onBoardingScreen1.subTitle': 'تسوق كل حاجياتك بمكان واحد',
          'onBoardingScreen2.title': 'عروض دائمة',
          'onBoardingScreen2.subTitle': 'عروض دائمة و الأسعار المنافسة',
          'onBoardingScreen3.title': 'توصيل خلال 30 دقيقة',
          'onBoardingScreen3.subTitle': 'توصيل خلال 30 دقيقة',
          'signinScreen.title': 'أهلاً بكم في سفن ديز مارت',
          'signinScreen.usernameTitle': 'الإيميل أو الموبايل',
          'signinScreen.password': 'كلمة المرور',
          'signinScreen.forgetPassword': 'نسيت كلمة المرور?',
          'signinScreen.signinAction': 'تسجيل الدخول',
          'signinScreen.signupAction': 'إنشاء حساب',
          'signupScreen.title': 'أهلاً بكم في سفن ديز مارت',
          'signupScreen.usernameTitle': 'الإيميل أو الموبايل',
          'signupScreen.fullName': 'الاسم الكامل',
          'signupScreen.password': 'كلمة المرور',
          'signupScreen.confirmPassword': 'تأكيد كلمة المرور',
          'signupScreen.phoneNumber': 'رقم الموبايل',
          'signupScreen.address': 'العنوان',
          'signupScreen.signupAction': 'إنشاء حساب',
          'signupScreen.signinAction': 'تسجيل الدخول',
          'change_language': 'تغيير اللغة',
          'languagesScreen.title': 'اختر اللغة',
          'languagesScreen.arabic': 'العربية',
          'languagesScreen.english': 'الإنجليزية',
          'languagesScreen.continue': 'المتابعة',
          'unauthorizedDialog.title': 'خطأ',
          'unauthorizedDialog.close': 'الغاء',
          'ViewErrorDialog.title': 'تنبيه',
          'ViewErrorDialog.close': 'الغاء',
          'homeScreen.searchFiled': 'ماذا تريد',
          'homeScreen.offerAction': 'قراءة المزيد',
          'homeScreen.title1': 'تسوق حسب الأصناف',
          'homeScreen.title2': 'الأكثر مبييعاً',
          'searchPage.trendingAreTitle': 'رائج',
          'searchPage.popularSearchAreTitle': 'شائعات البحث',
          'searchPage.searchFiled': 'ابحث عن ...',
          'searchPage.title': 'البحث',
          'ProductDetailsScreen.title': 'تفاصيل المنتج',
          'ProductDetailsScreen.descriptionTitle': 'الوصف',
          'ProductDetailsScreen.detailsTile': 'التفاصيل',
          'ProductDetailsScreen.price': 'السعر',
          'ProductDetailsScreen.unit': 'ل.س',
          'ProductDetailsScreen.specifications': 'المواصفات',
          'ProductDetailsScreen.purchase': 'شراء',
          'ProductDetailsScreen.addToCart': 'إضافة الى السلة',
          'ProductDetailsScreen.removeFromCart': 'إزالة من السلة',
          'ProductDetailsScreen.QTY': 'الكميةالمتوفرة',
          'ProductDetailsScreen.OOS': 'الكمية منتهية',
          'cartScreen.title': 'السلة',
          'cartScreen.deleteButton': 'حذف',
          'cartScreen.submit': 'شراء',
          'searchScreen.categories': 'الأصناف',
          'searchScreen.brands': 'البراندات',
          'searchScreen.close': 'تم',
          'checkout.title': 'تأكيد الطلب',
          'checkout.total': 'الكلفة الإجمالية',
          'checkout.proceed': 'إتمام الطلب',
          'checkout.Note': 'ملاحظات',
          'checkout.mobile': 'رقم موبايل آخر',
          'profileScreen.orderHistory': 'سجل الطلبات',
          'profileScreen.logout': 'تسجيل الخروج',
          'orderScreen.title': 'سجل الطلبات',
          'orderScreen.orderWord': 'الطلب',
          'orderScreen.responseNote': 'ملاحظة:',
          'orderScreen.anotherMobileTitle': 'رقم الموبايل البديل:',
          'orderScreen.userNote': 'ملاحظتك:',
          'orderScreen.canNotProceed': 'مشكلة في الكميات المطلوبة',
          'orderScreen.canNotProceedMessage': 'الكملية المطلوبة من المنتج',
          'orderScreen.canNotProceedMessage2': 'غير متوافرة يرجى تعديل الطلب',
          'orderScreen.availbleQTY': 'الكمية المتوفرة',
          'brandScreen.title': 'البراندات',
          'brandScreen.active': 'نشط',
          'brandScreen.inactive': 'غير نشط',
          'brandScreen.created': 'تم إنشاؤه',
          'brandScreen.updated': 'تم التحديث',
          'brandScreen.unknownBrand': 'الماركة غير معروفة',
          'brandScreen.website': 'الموقع الإلكتروني',
        },
      };

  // Get Current Locale
  static Locale getCurrentLocale() {
    return Get.locale ?? fallbackLocale;
  }

  // Change Language
  static void changeLocale(String? languageCode) {
    Locale locale =
        languageCode == 'en' ? Locale('en', 'US') : Locale('ar', 'EG');
    Get.updateLocale(locale);
  }
}
